package com.tichuclub.tichuclub

enum class TichuEvents {
    GRAND_TICHU_CALL_SKIPPED_BY_PLAYER,
    GRAND_TICHU_CALL_BY_PLAYER,
    GRAND_TICHU_CALL_BY_ZACH,
    GRAND_TICHU_CALL_BY_NATE,
    GRAND_TICHU_CALL_BY_THONG,
    GRAND_TICHU_CALLED,
    TICHU_CALL_BY_PLAYER,
    TICHU_CALL_BY_NATE,
    TICHU_CALL_BY_THONG,
    TICHU_CALL_BY_ZACH,
    ZACH_HAS_SPARROW,
    THONG_HAS_SPARROW,
    BRANDON_HAS_SPARROW,
    NATE_HAS_SPARROW,
    REACT_TO_CALL_BY_PLAYER,
    REACT_TO_CALL_BY_PARTNER
}